CREATE SCHEMA IF NOT EXISTS `pickup` DEFAULT CHARACTER SET utf8mb4;

GRANT ALL ON *.* TO 'kakao12'@'localhost' IDENTIFIED BY 'Kakao@123' WITH GRANT OPTION;
GRANT ALL ON pickup.* TO 'kakao12'@'localhost';
FLUSH PRIVILEGES;