spring:
  config:
    activate:
      on-profile: local-db
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false

  datasource:
    url: jdbc:h2:~/spring-qna-db
    driver-class-name: org.h2.Driver
    username: sa
    password: