server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  h2:
    console:
      enabled: true
logging:
  level:
    '[pickup_shuttle.pickup]': DEBUG
    '[org.hibernate.type]': TRACE