spring:
  config:
    activate:
      on-profile: dev-aws
cloud:
  aws:
    s3:
      bucket: pickup-shuttle-bucket
      dir : student-card/
    credentials:
      accessKey: ${AWS_ACCESSKEY}
      secretKey: ${AWS_SECRETKEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
